database:
  adapter: mysql2
  host: localhost
  database: generalstorespider
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: root
  password:

taobaoke:
  app_key: 28072206
  app_secret: 913600a3c0e71277544d675354b28f9b
  adzone_id: 109639900014
